### ISSUE TITLE
Link veraltet

### ISSUE THREAD

**Issue by patkan** [fau-fablab/spaceapi#2]
https://github.com/fau-fablab/spaceapi/blob/88a4d3bd89697804783951e65c31da6d37367d6a/spaceapi/spaceapi.py#L196

Der Link ist doch veraltet, oder?

**Comment by sedrubal** [comment]
Ja 👍

**Comment by sedrubal** [comment]
Erledigt mit b25f5a2 :wink:

**Comment by patkan** [comment]
Top! :-)
